version: '3.8'
services:
  dev:
    image: gilbertfrancois/c-programming-cookbook:latest
    command: tail -f /dev/null
    security_opt:
      - seccomp:unconfined
    volumes:
      - .:/workdir
    network_mode: "host"
